version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ldap-web-manager-postgres
    environment:
      POSTGRES_DB: ldap_manager
      POSTGRES_USER: ldap_manager
      POSTGRES_PASSWORD: ldap_manager_password
      POSTGRES_INITDB_ARGS: "-c shared_buffers=256MB -c max_connections=200"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ldap_manager"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ldap-network

  redis:
    image: redis:7-alpine
    container_name: ldap-web-manager-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ldap-network

  backend:
    image: quay.io/infrastructure-alexson/ldap-web-manager-backend:latest
    container_name: ldap-web-manager-backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://ldap_manager:ldap_manager_password@postgres:5432/ldap_manager
      REDIS_URL: redis://redis:6379/0
      LDAP_PRIMARY_SERVER: ldap1.svc.eh168.alexson.org
      LDAP_SECONDARY_SERVER: ldap2.svc.eh168.alexson.org
      LDAP_BASE_DN: dc=eh168,dc=alexson,dc=org
      JWT_SECRET: your-secret-key-change-in-production
      SECRET_KEY: your-secret-key-change-in-production
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - ldap-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  frontend:
    image: quay.io/infrastructure-alexson/ldap-web-manager-frontend:latest
    container_name: ldap-web-manager-frontend
    depends_on:
      - backend
    volumes:
      - ./nginx/sites-available/ldap-manager.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx-certs:/etc/nginx/certs:ro
    ports:
      - "8080:80"
      - "8443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - ldap-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  ldap-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

# Profiles for optional services
# postgres-backup:
#   image: postgres:16-alpine
#   container_name: ldap-web-manager-postgres-backup
#   depends_on:
#     postgres:
#       condition: service_healthy
#   volumes:
#     - postgres_backups:/backups
#   command: |
#     bash -c 'while true; do
#       pg_dump -h postgres -U ldap_manager ldap_manager | gzip > /backups/ldap_manager_$(date +\%Y\%m\%d_\%H\%M\%S).sql.gz
#       sleep 3600
#     done'
#   networks:
#     - ldap-network
#   profiles:
#     - backup

