apiVersion: v1
kind: Service
metadata:
  name: ldap-manager-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ldap-manager-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
