apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-manager-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: ldap-manager-frontend
    {{- include "ldap-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: ldap-manager-frontend
  template:
    metadata:
      labels:
        app: ldap-manager-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
