name: Build and Push GitHub Action Runner Image

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'docker/github-action-runner/**'
      - '.github/workflows/build-action-runner.yml'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'docker/github-action-runner/**'
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Push image to registry'
        required: false
        default: 'true'

env:
  REGISTRY: docker.io
  IMAGE_NAME: github-action-runner
  USERNAME: salexson

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-options: image=moby/buildkit:master

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/github-action-runner
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Create release notes
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "## Docker Image Released" > release_notes.md
          echo "" >> release_notes.md
          echo "**Image**: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:$TAG" >> release_notes.md
          echo "" >> release_notes.md
          echo "**Platforms**: linux/amd64, linux/arm64" >> release_notes.md
          echo "" >> release_notes.md
          echo "### Pull Command" >> release_notes.md
          echo "\`\`\`bash" >> release_notes.md
          echo "podman pull ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:$TAG" >> release_notes.md
          echo "\`\`\`" >> release_notes.md

      - name: Upload release notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: release-notes
          path: release_notes.md

