apiVersion: v1
kind: Pod
metadata:
  name: ldap-web-manager
  namespace: ldap-manager
spec:
  restartPolicy: Always
  
  containers:
  # Backend Service
  - name: backend
    image: quay.io/infrastructure-alexson/ldap-web-manager-backend:latest
    imagePullPolicy: IfNotPresent
    
    ports:
    - name: api
      containerPort: 8000
      hostPort: 8000
      protocol: TCP
    
    env:
    - name: DATABASE_URL
      value: "postgresql://ldap_manager:ldap_manager_password@postgres:5432/ldap_manager"
    - name: REDIS_URL
      value: "redis://redis:6379/0"
    - name: LDAP_PRIMARY_SERVER
      value: "ldap1.svc.eh168.alexson.org"
    - name: LDAP_SECONDARY_SERVER
      value: "ldap2.svc.eh168.alexson.org"
    - name: LDAP_BASE_DN
      value: "dc=eh168,dc=alexson,dc=org"
    - name: JWT_SECRET
      value: "your-secret-key-change-in-production"
    - name: SECRET_KEY
      value: "your-secret-key-change-in-production"
    
    volumeMounts:
    - name: config
      mountPath: /app/config
      readOnly: true
    - name: logs
      mountPath: /app/logs
    
    livenessProbe:
      httpGet:
        path: /health/live
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    
    readinessProbe:
      httpGet:
        path: /health/ready
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    
    startupProbe:
      httpGet:
        path: /health/startup
        port: 8000
      initialDelaySeconds: 0
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 30
    
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
    
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false

  # Frontend Service
  - name: frontend
    image: quay.io/infrastructure-alexson/ldap-web-manager-frontend:latest
    imagePullPolicy: IfNotPresent
    
    ports:
    - name: http
      containerPort: 80
      hostPort: 8080
      protocol: TCP
    - name: https
      containerPort: 443
      hostPort: 8443
      protocol: TCP
    
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    - name: nginx-certs
      mountPath: /etc/nginx/certs
      readOnly: true
    - name: nginx-cache
      mountPath: /var/cache/nginx
    
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    
    securityContext:
      runAsNonRoot: true
      runAsUser: 101
      capabilities:
        drop:
        - ALL
        add:
        - CHOWN
        - SETGID
        - SETUID
        - DAC_OVERRIDE
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false

  # PostgreSQL Database
  - name: postgres
    image: postgres:16-alpine
    imagePullPolicy: IfNotPresent
    
    ports:
    - name: postgres
      containerPort: 5432
      protocol: TCP
    
    env:
    - name: POSTGRES_DB
      value: "ldap_manager"
    - name: POSTGRES_USER
      value: "ldap_manager"
    - name: POSTGRES_PASSWORD
      value: "ldap_manager_password"
    - name: POSTGRES_INITDB_ARGS
      value: "-c shared_buffers=256MB -c max_connections=200"
    
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
    - name: postgres-init
      mountPath: /docker-entrypoint-initdb.d
      readOnly: true
    
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - pg_isready -U ldap_manager
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - pg_isready -U ldap_manager
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

  # Redis Cache
  - name: redis
    image: redis:7-alpine
    imagePullPolicy: IfNotPresent
    
    ports:
    - name: redis
      containerPort: 6379
      protocol: TCP
    
    command:
    - redis-server
    - "--appendonly"
    - "yes"
    - "--maxmemory"
    - "256mb"
    - "--maxmemory-policy"
    - "allkeys-lru"
    
    volumeMounts:
    - name: redis-data
      mountPath: /data
    
    livenessProbe:
      exec:
        command:
        - redis-cli
        - ping
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    
    readinessProbe:
      exec:
        command:
        - redis-cli
        - ping
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"

  # Volumes
  volumes:
  - name: config
    hostPath:
      path: /etc/ldap-web-manager/config
      type: Directory
  
  - name: logs
    hostPath:
      path: /var/log/ldap-web-manager
      type: DirectoryOrCreate
  
  - name: nginx-config
    hostPath:
      path: /etc/ldap-web-manager/nginx/conf.d
      type: Directory
  
  - name: nginx-certs
    hostPath:
      path: /etc/ldap-web-manager/nginx/certs
      type: Directory
  
  - name: nginx-cache
    emptyDir:
      medium: Memory
      sizeLimit: 256Mi
  
  - name: postgres-data
    hostPath:
      path: /var/lib/ldap-web-manager/postgres
      type: DirectoryOrCreate
  
  - name: postgres-init
    hostPath:
      path: /etc/ldap-web-manager/postgres-init
      type: Directory
  
  - name: redis-data
    hostPath:
      path: /var/lib/ldap-web-manager/redis
      type: DirectoryOrCreate
  
  # Pod Security and Network
  securityContext:
    seLinuxOptions:
      level: "s0:c123,c456"
  
  dnsPolicy: ClusterFirst
  hostNetwork: false
  shareProcessNamespace: true

---

# Service definition (if using Kubernetes-like networking)
apiVersion: v1
kind: Service
metadata:
  name: ldap-web-manager-backend
  namespace: ldap-manager
spec:
  selector:
    app: ldap-web-manager
    component: backend
  ports:
  - name: api
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: ldap-web-manager-frontend
  namespace: ldap-manager
spec:
  selector:
    app: ldap-web-manager
    component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  type: LoadBalancer

